### ISSUE TITLE
Inconsistent logo on Google Play?

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/simple-obfs-android#1]
The same applies to kcptun-android.

Google Play uses a different hi-res icon than this app. Should we update either of them or keep it as is?

**Comment by madeye** [comment]
I don't know why simple-obfs has this issue.

The reason why kcptun's icons are different is that I cannot find a high-res icon from kcptun project. So I generated one for bypassing Google Play's check.

**Comment by madeye** [comment]
OK, I found the problem. It's just because I forgot to update the high-res icon for simple-obfs...

**Comment by Mygod** [comment]
Okay... I've fixed that. Maybe we should ask @xtaci to recreate a hi-res icon?

**Comment by madeye** [comment]
Sure.

**Comment by Mygod** [comment]
I'm creating one currently. Closing this for now.
