### ISSUE TITLE
用nginx反代simple obfs服务端情况下，android端的obfs数据不能正确转发

### ISSUE THREAD

**Issue by hannnnn-l** [shadowsocks/simple-obfs-android#11]
nginx在服务器80口建立一个http服务器，配置websocket转发到simple obfs的服务端口8800，windows和shadowrocket的数据流都正常转发，但android端的数据不能正确被识别为websocket。
log：114.242.248.70 - - [13/Feb/2018:12:04:57 +0800] "GET / HTTP/1.1" 301 178 "-" "curl/7.39.1"
客户端配置：
插件：obfs-local
模式：http
obfs-host：test.example.com (example位置是我的网址）

**Comment by ghost** [comment]
目前最新的Android obfs安装插件（安装包版本0.0.5）所使用的obfs-local核心版本为0.0.2，应该是考虑到了旧版本兼容性的问题， 这个版本是不支持完整Websockets的。
具体的核心版本可以使用adb shell或者其它终端模拟器执行：
```
su -c /data/data/com.github.shadowsocks.plugin.obfs_local/lib/libobfs-local.so
```
查看到。

**Comment by love4taylor** [comment]
自己编译一下这个 repo 吧...

**Comment by hannnnn-l** [comment]
@slurin 明白了，谢谢！
@Love4Taylor 我自己编译一下试试。

**Comment by Mygod** [comment]
Questions should go to [discourse forum](https://discourse.shadowsocks.org/c/implementations/shadowsocks-android) with tag plugin.

**Comment by MNTMDEV** [comment]
这个版本的包缺少Content-Length头，做不了反代
