### ISSUE TITLE
add more options in feature settings

### ISSUE THREAD

**Issue by eXtrem0us** [shadowsocks/simple-obfs-android#12]
I set this setting in server side:
**"plugin_opts":"obfs=tls;failover=127.0.0.1:8443;fast-open"**
Then I intended to apply identical settings on my android phone, but there are limited settings in the app.

However I managed to escape this obstacle in two steps:
first, by changing the server side setting by adding _obfs-host_ field:
**"obfs=tls;obsf-host=bing.com;failover=127.0.0.1:8443;fast-open"**
...and then in app, I mocked the needed setting by changing the _Obfuscation hostname_ to this:
**bing.com;failover=127.0.0.1:8443;fast-open**

but, it doesn't look like a good solution.

**Comment by Mygod** [comment]
You do not need to specify failover nor fast-open on your client. Also that shouldn't work.
