### ISSUE TITLE
编译过程中的小问题

### ISSUE THREAD

**Issue by fanck0605** [shadowsocks/simple-obfs-android#13]
![image](https://user-images.githubusercontent.com/28819315/42755505-05d4186a-892b-11e8-97db-7ce5bae1f023.png)
It seems a Bug,but I sucessfully generated the apk(no test)

**Comment by Mygod** [comment]
Questions should go to [discourse forum](https://discourse.shadowsocks.org/c/implementations/shadowsocks-android) with tag plugin.
