### ISSUE TITLE
Cannot use with remote dns option.

### ISSUE THREAD

**Issue by abraaocaldas** [shadowsocks/simple-obfs-android#2]
When I select the option to forward all the traffic to remote server on ShadowSocks Android + obfs plugin the traffic is not forwarded but with the option turned off everything works.

**Comment by Mygod** [comment]
Did you mean DNS forwarding?

**Comment by abraaocaldas** [comment]
Yes, exactly.

**Comment by Mygod** [comment]
It won't work. Disable DNS forwarding.

**Comment by triaqu** [comment]
Is it possible support UDP  forwarding further?

**Comment by l1viathan** [comment]
Would you please document this somewhere?  e.g.  at the Android app, give some hints about the co-exsisting issue of DNS forwarding and obfs.

I spent quite a while on it, not been aware that it was obfs-related :(
