### ISSUE TITLE
连不上的问题

### ISSUE THREAD

**Issue by sniperhalo** [shadowsocks/simple-obfs-android#9]
这个插件是需要服务端吗？
这个软件hostname设置的网站是干啥的？
配合shadowsocks需要设置什么参数吗？
是直接链接用的吗？
没有文档第一次使用完全连不上啊

**Comment by Xiangsong-Guan** [comment]
参见https://github.com/shadowsocks/simple-obfs

**Comment by Mygod** [comment]
Questions should go to [discourse forum](https://discourse.shadowsocks.org/c/implementations/shadowsocks-android) with tag plugin.
